// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyz0UYATfHGjD4ORrggMw9YcBUe5_aJ78',
    appId: '1:35323379955:web:670c8d89b9f43ad165f786',
    messagingSenderId: '35323379955',
    projectId: 'sport1flutter',
    authDomain: 'sport1flutter.firebaseapp.com',
    storageBucket: 'sport1flutter.appspot.com',
    measurementId: 'G-5C3BK9ZSM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHAwEH8fMO0kOx76hCvKAJK6F8sPa2LoY',
    appId: '1:35323379955:android:525ddde819be2a6b65f786',
    messagingSenderId: '35323379955',
    projectId: 'sport1flutter',
    storageBucket: 'sport1flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjEmPUeT3BbZ9wCZ_fuUlZGpSjISlkb_A',
    appId: '1:35323379955:ios:0752e7e2bc297b6565f786',
    messagingSenderId: '35323379955',
    projectId: 'sport1flutter',
    storageBucket: 'sport1flutter.appspot.com',
    iosClientId: '35323379955-f09d52pdnreob4bnbco9r49uh2f9tn71.apps.googleusercontent.com',
    iosBundleId: 'com.example.sport1',
  );
}
